version: '3'

services: 
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks: 
      - node-challenge-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
     - "3000:3000"
    depends_on: 
      - db

  nginx_challenge:
    build:
      context: ./nginx
    image: thuron/nginx
    container_name: nginx
    networks:
      - node-challenge-network
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes: 
     - ./mysql:/var/lib/mysql
     - ./dump:/docker-entrypoint-initdb.d
    environment: 
     - MYSQL_DATABASE=challengedb
     - MYSQL_ROOT_PASSWORD=root
    networks: 
     - node-challenge-network

networks: 
  node-challenge-network:
    driver: bridge